In [1]:
import os
from pathlib import Path
os.chdir(Path(os.getcwd()).parent)

In [2]:
import os
import time
import pandas as pd
import cvxpy as cp
from pathlib import Path
from Code.Plotting import DPhil_Plotting
from Code.Network.Network import Network_STEVFNs
from Code.Results.GMPA_Results_original import export_results

case_study_name = "MY-SG_Collab"

base_folder = Path(os.getcwd())
data_folder = os.path.join(base_folder, "Data")
case_study_folder = os.path.join(data_folder, "Case_Study", case_study_name)
scenario_folders_list = [x[0] for x in os.walk(case_study_folder)][1:]
network_structure_filename = os.path.join(case_study_folder, "Network_Structure.csv")
results_filename = os.path.join(case_study_folder, "total_data.csv")
website_total_data_filename = os.path.join(case_study_folder, "total_data_unrounded.csv")
capacities_filename = os.path.join(case_study_folder, "capacities_total_data.csv")
unrounded_results_filename = os.path.join(case_study_folder, "internal_total_data.csv")

network_structure_df = pd.read_csv(network_structure_filename)

print("========================== Building ==========================")
start_time0 = time.time()
my_network = Network_STEVFNs()
my_network.build(network_structure_df)
end_time = time.time()
print("Time taken to build network = ", end_time - start_time0, "s")

results = list()
for counter1 in range(len(scenario_folders_list)):

    scenario_folder = scenario_folders_list[-1-counter1]
    asset_parameters_filename = os.path.join(scenario_folder, "Asset_Parameters.csv")
    location_parameters_filename = os.path.join(scenario_folder, "Location_Parameters.csv")
    system_parameters_filename = os.path.join(scenario_folder, "System_Parameters.csv")

    asset_parameters_df = pd.read_csv(asset_parameters_filename)
    location_parameters_df = pd.read_csv(location_parameters_filename)
    system_parameters_df = pd.read_csv(system_parameters_filename)
    my_network.scenario_name = os.path.basename(scenario_folder)

    print(f"\n================== Updating for Scenario {my_network.scenario_name} ==================\n")
    start_time = time.time()
    my_network.update(location_parameters_df, asset_parameters_df, system_parameters_df)
    end_time = time.time()
    print("Time taken to update network = ", end_time - start_time, "s")

    start_time = time.time()
    solver_name = "CLARABEL"
    if solver_name == "CLARABEL":
        my_network.problem.solve(solver=cp.CLARABEL, max_iter=10000, ignore_dpp=True)
    elif solver_name == "MOSEK":
        my_network.problem.solve(solver=cp.MOSEK, ignore_dpp=True)
    else:
        raise ValueError(f"Unknown solver: {solver_name}")
    end_time = time.time()

    print(f"----------------- Scenario {my_network.scenario_name} Main Results ----------------------\n")
    print("Time taken to solve problem = ", end_time - start_time, "s")
    print(my_network.problem.solution.status) # type: ignore
    if my_network.problem.value == float("inf"):
        continue
    print("Total cost to satisfy all demand = ", my_network.problem.value, " Billion USD")
    print("Total emissions = ", my_network.assets[0].asset_size(), "MtCO2e")

    results.append({
        "carbon_budget": "/".join(scenario_folder.split("/")[-2:]),
        "network": my_network
    })

========================== Building ==========================

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

Time taken to build network =  14.703842639923096 s

================== Updating for Scenario 30 ==================

Time taken to update network =  0.07214999198913574 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 30 Main Results ----------------------

Time taken to solve problem =  15.55990719795227 s
optimal
Total cost to satisfy all demand =  413.7935952577719  Billion USD
Total emissions =  1169.999999976118 MtCO2e

================== Updating for Scenario 0 ==================

Time taken to update network =  0.06999635696411133 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 0 Main Results ----------------------

Time taken to solve problem =  13.891085624694824 s
optimal
Total cost to satisfy all demand =  467.46490588526035  Billion USD
Total emissions =  418.39529425260935 MtCO2e

================== Updating for Scenario 10 ==================

Time taken to update network =  0.07002854347229004 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 10 Main Results ----------------------

Time taken to solve problem =  13.734025716781616 s
optimal
Total cost to satisfy all demand =  448.95548303028323  Billion USD
Total emissions =  585.5014101399615 MtCO2e

================== Updating for Scenario 60 ==================

Time taken to update network =  0.06909513473510742 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 60 Main Results ----------------------

Time taken to solve problem =  13.969880104064941 s
optimal
Total cost to satisfy all demand =  393.5981648649541  Billion USD
Total emissions =  1759.9999998926858 MtCO2e

================== Updating for Scenario 40 ==================

Time taken to update network =  0.06946897506713867 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 40 Main Results ----------------------

Time taken to solve problem =  13.436232328414917 s
optimal
Total cost to satisfy all demand =  410.0576681111939  Billion USD
Total emissions =  1259.9999999803301 MtCO2e

================== Updating for Scenario BAU ==================

Time taken to update network =  0.0686194896697998 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario BAU Main Results ----------------------

Time taken to solve problem =  13.658844709396362 s
optimal
Total cost to satisfy all demand =  571.0163746167432  Billion USD
Total emissions =  2.208112366086477e-05 MtCO2e

================== Updating for Scenario 90 ==================

Time taken to update network =  0.07313871383666992 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 90 Main Results ----------------------

Time taken to solve problem =  13.537604331970215 s
optimal
Total cost to satisfy all demand =  379.6387292189949  Billion USD
Total emissions =  2509.9999997668574 MtCO2e

================== Updating for Scenario 50 ==================

Time taken to update network =  0.0697484016418457 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 50 Main Results ----------------------

Time taken to solve problem =  13.743008852005005 s
optimal
Total cost to satisfy all demand =  396.0724737180543  Billion USD
Total emissions =  1669.9999999647666 MtCO2e

================== Updating for Scenario 70 ==================

Time taken to update network =  0.06856346130371094 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 70 Main Results ----------------------

Time taken to solve problem =  13.510546445846558 s
optimal
Total cost to satisfy all demand =  386.35732154489256  Billion USD
Total emissions =  2089.9999999433085 MtCO2e

================== Updating for Scenario 20 ==================

Time taken to update network =  0.0698707103729248 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 20 Main Results ----------------------

Time taken to solve problem =  13.812292098999023 s
optimal
Total cost to satisfy all demand =  430.38357031715935  Billion USD
Total emissions =  836.790588989503 MtCO2e

================== Updating for Scenario 80 ==================

Time taken to update network =  0.0696568489074707 s

/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #0 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #40 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "
/home/jpacilo/Developer/ce2m/urbs/.venv/lib/python3.12/site-packages/cvxpy/problems/problem.py:173: UserWarning: Constraint #70 contains too many subexpressions. Consider vectorizing your CVXPY code to speed up compilation.
  warnings.warn(f"Constraint #{i} contains too many subexpressions. "

----------------- Scenario 80 Main Results ----------------------

Time taken to solve problem =  13.53559684753418 s
optimal
Total cost to satisfy all demand =  382.0552518492879  Billion USD
Total emissions =  2339.9999998203343 MtCO2e

In [15]:
network_df = pd.DataFrame(results)
network_df = network_df.sort_values(by="carbon_budget")
network_df = network_df.reset_index(drop=True)

network = network_df.loc[len(network_df) - 1, "network"] # BAU

country_code_mapping = {
    "_0_": "_[SG]_",
    "_2_": "_[MY]_",
    "_2-0_": "_[MY]-[SG]_",
    "_0-2_": "_[SG]-[MY]_",
}
data = export_results(my_network)
data.iloc[:, 1] = data.iloc[:, 1].replace(country_code_mapping, regex=True)
data.iloc[:, 3] = data.iloc[:, 3].replace(country_code_mapping, regex=True)
data = data.reset_index().drop(columns="Number")
data.columns = ["Costs", "Asset_Name__Costs", "Sizes", "Asset_Name__Sizes"]
data = data.sort_values(by="Asset_Name__Sizes").reset_index(drop=True)
data = data.round(4)
network_data = data

In [16]:
simulated_timesteps = network.system_structure_properties["simulated_timesteps"]
simulated_timesteps

720

In [18]:
(data.loc[3, "Sizes"] * (8760)) / 1e3

np.float64(301.029516)

In [19]:
(data.loc[4, "Sizes"] * (8760)) / 1e3

np.float64(93.413136)

In [20]:
asset_id = "EL_Demand_[SG]_GWh"
el_demand_sg_gwh = data.loc[data.iloc[:, 3]==asset_id, "Sizes"].item() # * (8760 / simulated_timesteps)
el_demand_sg_gwh

10.6636

In [21]:
network.assets[4].parameters_df

Type                           2
sizing_constant         1.446743
sizing_constant_unit      G$/GWp
lifespan                  262800
lifespan_unit                  h
RE_type                  WINDOUT
set_size                      24
set_number                     0
maximum_size            100.2662
maximum_size_unit            GWp
location_name                MYS
Name: 2, dtype: object

In [22]:
asset_ids = sorted(data.loc[data.iloc[:, 3].apply(lambda x: ("Budget" not in x) and ("HTH" not in x))].iloc[:, 3].tolist())

generations = list()
for asset_id in asset_ids:
    if asset_id.split("_")[-1] == "GW":
        generation_gwh = data.loc[data.iloc[:, 3]==asset_id, "Sizes"].item() * simulated_timesteps # 8760
    elif asset_id.split("_")[-1] == "GWh":
        generation_gwh = data.loc[data.iloc[:, 3]==asset_id, "Sizes"].item() * 1  # (8760 / simulated_timesteps)
    generations.append(generation_gwh)

pd.DataFrame({"asset_id": asset_ids, "el_generation_in_gwh": generations})

                        asset_id  el_generation_in_gwh
0                  BESS_[MY]_GWh               24.4350
1                  BESS_[SG]_GWh                0.0006
2             EL_Demand_[MY]_GWh               34.3641
3             EL_Demand_[SG]_GWh               10.6636
4      EL_Transport_[MY]-[SG]_GW             8410.5360
5              EL_to_NH3_[MY]_GW                0.0000
6              EL_to_NH3_[SG]_GW                0.0000
7           NH3_Storage_[MY]_GWh                0.0001
8           NH3_Storage_[SG]_GWh                0.0001
9     NH3_Transport_[MY]-[SG]_GW                0.0000
10             NH3_to_EL_[MY]_GW                0.0000
11             NH3_to_EL_[SG]_GW                0.0000
12                PP_CO2_[MY]_GW            20764.0800
13                PP_CO2_[SG]_GW                0.0000
14   RE_PV_Openfield_Lim_[MY]_GW            59902.1280
15   RE_PV_Openfield_Lim_[SG]_GW              254.4480
16     RE_PV_Rooftop_Lim_[MY]_GW                0.0000
17     RE_PV_Rooftop_Lim_[SG]_GW                0.0000
18  RE_WIND_Offshore_Lim_[MY]_GW                0.0000
19  RE_WIND_Offshore_Lim_[SG]_GW                0.0000
20   RE_WIND_Onshore_Lim_[MY]_GW            70627.1040
21   RE_WIND_Onshore_Lim_[SG]_GW                0.0000

In [23]:
data.loc[data.iloc[:, 3].apply(lambda x: ("_[SG]_" in x) and ("HTH" not in x))]

,Costs,Asset_Name__Costs,Sizes,Asset_Name__Sizes
1,0.0003203250805603706,BESS_[SG]_G$,0.0006,BESS_[SG]_GWh
4,0.0,EL_Demand_[SG]_G$,10.6636,EL_Demand_[SG]_GWh
9,0.000008,EL_to_NH3_[SG]_G$,0.0000,EL_to_NH3_[SG]_GW
15,0.000033,NH3_Storage_[SG]_G$,0.0001,NH3_Storage_[SG]_GWh
18,0.000024,NH3_to_EL_[SG]_G$,0.0000,NH3_to_EL_[SG]_GW
22,0.000069,PP_CO2_[SG]_G$,0.0000,PP_CO2_[SG]_GW
24,0.180229,RE_PV_Openfield_Lim_[SG]_G$,0.3534,RE_PV_Openfield_Lim_[SG]_GW
26,0.0,RE_PV_Rooftop_Lim_[SG]_G$,0.0000,RE_PV_Rooftop_Lim_[SG]_GW
28,0.000001,RE_WIND_Offshore_Lim_[SG]_G$,0.0000,RE_WIND_Offshore_Lim_[SG]_GW
30,0.000001,RE_WIND_Onshore_Lim_[SG]_G$,0.0000,RE_WIND_Onshore_Lim_[SG]_GW

In [24]:
data.loc[data.iloc[:, 3].apply(lambda x: ("_[MY]_" in x) and ("HTH" not in x))]

,Costs,Asset_Name__Costs,Sizes,Asset_Name__Sizes
0,13.182841557211917,BESS_[MY]_G$,24.4350,BESS_[MY]_GWh
3,0.0,EL_Demand_[MY]_G$,34.3641,EL_Demand_[MY]_GWh
8,0.000014,EL_to_NH3_[MY]_G$,0.0000,EL_to_NH3_[MY]_GW
14,0.000031,NH3_Storage_[MY]_G$,0.0001,NH3_Storage_[MY]_GWh
17,0.000023,NH3_to_EL_[MY]_G$,0.0000,NH3_to_EL_[MY]_GW
21,109.219507,PP_CO2_[MY]_G$,28.8390,PP_CO2_[MY]_GW
23,42.430656,RE_PV_Openfield_Lim_[MY]_G$,83.1974,RE_PV_Openfield_Lim_[MY]_GW
25,0.0,RE_PV_Rooftop_Lim_[MY]_G$,0.0000,RE_PV_Rooftop_Lim_[MY]_GW
27,0.0,RE_WIND_Offshore_Lim_[MY]_G$,0.0000,RE_WIND_Offshore_Lim_[MY]_GW
29,141.91572,RE_WIND_Onshore_Lim_[MY]_G$,98.0932,RE_WIND_Onshore_Lim_[MY]_GW